### ISSUE TITLE
5v5 Replacer

### ISSUE THREAD

**Issue by pietroluongo** [VSSSLeague/VSSReferee#17]
**Is your feature request related to a problem? Please describe.**
The VSSSReferee replacer module won't work properly with five robots, placing them incorrectly on the field or not moving them at all.

**Describe the solution you'd like**
The replacer should properly place the robots on situations like free kicks and other associated fouls. To achieve this, the replacer should have some logic concerning where exactly to place each robot, even with five players on the field.

**Comment by zsmn** [comment]
Solved at c792f76a86a0d2d39813b97937aa55f68a6c5b70
