### ISSUE TITLE
Wrong foul name sent by the referee in HALT case

### ISSUE THREAD

**Issue by Ana-Monici** [VSSSLeague/VSSReferee#23]
**Bug description**
The message sent by the referee has wrong foul name in the case of the HALT foul, instead of sending 'HALT', it send the int '7'.

**Replicate the error**
First we saved the command sent by referee in the 'status' variable:
c = vssref_command_pb2.VSSRef_Command()
data = self.referee_sock.recv(1024)
c.ParseFromString(data)
self._status = json.loads(MessageToJson(c))

Then we printed the current foul:
print(self._status.get('foul'))

When the HALT foul is triggered, the print is as follows:
7 (int)

**Expected behavior**
The expected behavior is the string 'HALT'.

**Desktop:**
 OS: Ubuntu 20.04.1

**Additional context**
The programming language used was python3.

**Comment by makitayukio** [comment]
Essa Issue já foi corrigida?

**Comment by zsmn** [comment]
Acredito que isso seja o comportamento natural sobre como o componente `Foul` funciona, já que ele é um enum. Vocês podem consultar os valores numéricos esperados para cada falta [aqui](https://github.com/VSSSLeague/VSSReferee/blob/CBFRS/include/proto/vssref_common.proto#L5).
Se vocês quiserem salvar a string especificamente, podem fazer uma abordagem semelhante a [esta](https://github.com/VSSSLeague/VSSReferee/blob/CBFRS/src/world/entities/referee/referee.cpp#L324), utilizando a função nativa `VSSRef::Foul_Name(VSSRef::Foul foul)`.
